# Предложения по аренде
## Получить все предложения
GET http://localhost:3006/suggestions
Content-Type: application/json

###

## Создание предложения
POST http://localhost:3006/suggestions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1ek1pY2gxOTk0QG1haWwucnUiLCJmaXJzdE5hbWUiOiJLdXoiLCJsYXN0TmFtZSI6Ik1pY2giLCJpZCI6IjY4YTFhNWQzYzM0MzM5MmZjODI1ODY0YyIsImlhdCI6MTc1NjIyNDA5MywiZXhwIjoxNzU2MjI0NjkzfQ.akWkSXGOlJw_sJ2YopmUT9pkNmmkWYEpTWXtQC4t9I4

{
  "title": "New Suggestion",
  "description": "Description of Description",
  "city": "Paris",
  "imagePreview": "img.jpeg",
  "publishedDate": "2025-08-20T11:28:44.855Z",
  "imagesGallery": [
    "img.jpeg",
    "img1.jpeg",
    "img1.jpeg",
    "img1.jpeg",
    "img1.jpeg",
    "img1.jpeg"
  ],
  "suggestionType": "apartment",
  "roomsCount": 1,
  "guestCount": 2,
  "rentPrice": 3000,
  "conveniences": [
    "washer"
  ],
  "coordinates": {
    "longitude": 10.000654,
    "latitude": 53.550341
  },
  "premium": false,
  "favourite": true
}

###

## Редактирование предложения
PATCH http://localhost:3006/suggestions/update/689a32d7e784e798712367c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1ek1pY2gxOTk0QG1haWwucnUiLCJmaXJzdE5hbWUiOiJLdXoiLCJsYXN0TmFtZSI6Ik1pY2giLCJpZCI6IjY4YTFhNWQzYzM0MzM5MmZjODI1ODY0YyIsImlhdCI6MTc1NjIyMjc3NSwiZXhwIjoxNzU2MjIzMzc1fQ.j8jM9q9xNgAX_XzRtDrh1Iv0ggiDX-7ptE6kjbRp_UE

{
  "title": "New suggestion of patch"
}

###

## Удаление предложения
DELETE http://localhost:3006/suggestions/689a32d7e784e798712367c3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1ek1pY2gxOTk0QG1haWwucnUiLCJmaXJzdE5hbWUiOiJLdXoiLCJsYXN0TmFtZSI6Ik1pY2giLCJpZCI6IjY4YTFhNWQzYzM0MzM5MmZjODI1ODY0YyIsImlhdCI6MTc1NjIyNDA5MywiZXhwIjoxNzU2MjI0NjkzfQ.akWkSXGOlJw_sJ2YopmUT9pkNmmkWYEpTWXtQC4t9I4

###

## Найти предложение по id
GET http://localhost:3006/suggestions/68adda8c69138fc08ecb77fa
Content-Type: application/json

###

## Получение сортированного по дате списка предложений
GET http://localhost:3006/suggestions/findNew?count=10
Content-Type: application/json

###

## Получение избранных предложений
GET http://localhost:3006/suggestions/findFavourite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imt1ek1pY2gxOTk0QG1haWwucnUiLCJmaXJzdE5hbWUiOiJLdXoiLCJsYXN0TmFtZSI6Ik1pY2giLCJpZCI6IjY4YTFhNWQzYzM0MzM5MmZjODI1ODY0YyIsImlhdCI6MTc1NjIyNDA5MywiZXhwIjoxNzU2MjI0NjkzfQ.akWkSXGOlJw_sJ2YopmUT9pkNmmkWYEpTWXtQC4t9I4

###

## Получение премиальных предложений
GET http://localhost:3006/suggestions/findPremium
Content-Type: application/json

###
