# Предложения по аренде
## Получить все предложения
GET http://localhost:3006/suggestions
Content-Type: application/json

###

## Создание предложения
POST http://localhost:3006/suggestions
Content-Type: application/json

{
  "title": "New Suggestion",
  "description": "Description of Description",
  "city": "Paris",
  "imagePreview": "img.jpeg",
  "publishedDate": "2025-08-20T11:28:44.855Z",
  "imagesGallery": [
    "img.jpeg",
    "img1.jpeg",
    "img1.jpeg",
    "img1.jpeg",
    "img1.jpeg",
    "img1.jpeg"
  ],
  "suggestionType": "apartment",
  "roomsCount": 1,
  "guestCount": 2,
  "rentPrice": 3000,
  "conveniences": [
    "washer"
  ],
  "coordinates": {
    "longitude": 10.000654,
    "latitude": 53.550341
  },
  "premium": false,
  "authorId": "68a1a5d3c343392fc825864c"
}

###

## Редактирование предложения
PATCH http://localhost:3006/suggestions/update/689a32d7e784e798712367c3
Content-Type: application/json

{
  "title": "New suggestion of patch"
}

###

## Удаление предложения
DELETE http://localhost:3006/suggestions/689a32d7e784e798712367bf
Content-Type: application/json

###

## Найти предложение по id
GET http://localhost:3006/suggestions/689a32d7e784e798712367c3
Content-Type: application/json

###

## Получение сортированного по дате списка предложений
GET http://localhost:3006/suggestions/findNew?count=10
Content-Type: application/json

###

## Получение избранных предложений
GET http://localhost:3006/suggestions/findFavourite
Content-Type: application/json

###

## Получение премиальных предложений
GET http://localhost:3006/suggestions/findPremium
Content-Type: application/json

###
