# Пользователи
## Получить пользователя по id
GET http://localhost:3006/user/689a32d7e784e798712367bd
Content-Type: application/json

###

## Регистрация нового пользователя
POST http://localhost:3006/user
Content-Type: application/json

{
  "email": "kuzMich1@mail.ru",
  "password": "123456",
  "firstName": "Kuz",
  "lastName": "Mich",
  "type": "pro"
}

###

## Обноврение пользователя по id
PUT http://localhost:3006/user/update/68a1a5d3c343392fc825864
Content-Type: application/json

{
  "email": "kuzMich1994@mail.ru"
}

###

## Авторизация
POST http://localhost:3006/user/login
Content-Type: application/json

{
  "email": "kuzMich1994@mail.ru",
  "password": "123456"
}
