# Комментарии
## Добавление комментария
POST http://localhost:3006/comments
Content-Type: application/json

{
  "text": "Comment 6",
  "rating": 2,
  "authorId": "68a1b6356a3a40047fea5579",
  "suggestionId": "68a1b5f0498bfb3cb3371160"
}

###

## Получить все комментарии
GET http://localhost:3006/comments
Content-Type: application/json

###

## Получить все комментарии по id предложения
GET http://localhost:3006/comments/68a1b5f0498bfb3cb3371160
Content-Type: application/json

###
